### ISSUE TITLE
Polyhedral Contract Syntax

### ISSUE THREAD

**Issue by NicolasRouquette** [pacti-org/pacti#129]
With: 

```
from pacti.utils.string_contract import StrContract
from pacti.terms.polyhedra.loaders import string_to_polyhedra_contract
```

We can write contracts in a human-friendly way like this:

```
# PWR:
# Parameters:
# - s: start index of the timeline variables
# - tstart: scheduled task instance start time
# - duration: scheduled task instance duration
# - generation: rate of battery charge during the task instance
def PWR_contract(s: int, tstart: float, duration: float, generation: float) -> tuple[int, list[IoContract]]:
  e = s+1
  spec = StrContract(
    inputs = [
      f"t{s}",    # Scheduled start time
      f"soc{s}",  # initial battery SOC
      f"d{s}",    # initial data volume
      f"e{s}",    # initial trajectory error
      f"r{s}",    # initial relative distance
    ],
    outputs = [
      f"t{e}",    # Scheduled end time
      f"soc{e}",  # final battery SOC
      f"d{e}",    # final data volume
      f"e{e}",    # final trajectory error
      f"r{e}",    # final relative distance
    ],
    assumptions = [
      # Scheduled task instance start time
      # t{s} == tstart
      f"t{s} <= {tstart}",
      f"-t{s} <= -{tstart}",
    ],
    guarantees = [
      # Scheduled task instance end time
      # t{e} - t{s} = duration
      f"t{e} - t{s} <= {duration}",
      f"t{s} - t{e} <= -{duration}",
    
      # Battery SOC charge
      # soc{e} - soc{s} >= duration*generation 
      f"soc{e} - soc{s} >= {duration*generation}",

      # no change to data volume
      # d{e} = d{s}
      f"d{e} - d{s} <= 0",
      f"d{s} - d{e} <= 0",

      # no change to trajectory error
      # e{e} = e{s}
      f"e{e} - e{s} <= 0",
      f"e{s} - e{e} <= 0",

      # no change to relative distance
      # r{e} = r{s}
      f"r{e} - r{s} <= 0",
      f"r{s} - r{e} <= 0",
    ])
  return e, string_to_polyhedra_contract(spec)
```

This approach delegates parsing the string expressions to Sympy, which accepts expressions that are not Polyhedral.
The resulting error messages can be difficult for users to understand.

This issue is about defining the syntax of Polyhedra constraints for parsing and rendering sketched as follows:

1) `LHS <= RHS`

where:

- `RHS` is a numerical constant
- `LHS` is of the form: `\sigma c V` where `c` is a constant, `V` is a variable.

For convenience, the following forms would be supported by rewrite as conjunctions of (1) above:

2) `| LHS | <= RHS`

Rewrite as the conjunction of:

- `LHS <= RHS`
- `-(LHS) <= RHS`

3) `| LHS | = 0`

Rewrite as the conjunction of:

- `LHS <= 0`
- `-(LHS) <= 0`

4) `LHS = RHS`

Rewrite as the conjunction of:

- `LHS <= RHS`
- `- (LHS) <= -(RHS)`

In the above:

- `-(RHS)` means negating the sign of the `RHS` constant
    e.g. `-(4)` becomes `-4` and `-(-3)` becomes `3` and `-(+2)` becomes `-2`
- `-(LHS)` means negating the effective sign of each atomic `c V` term in the `LHS` expression 
    e.g., `-(x-y)` becomes `-x+y`

The parser would reject any string expression that does not match any of (1,2,3,4).

This ticket entails two parts:

- [x] Parser

  This involves updating `pacti.terms.polyhedra.loaders.string_to_polyhedra_contract` to implement Regex-based parsing for the forms (1,2,3,4) above instead of using `Sympy`.

- [x] Pretty-printer

  Mapping the `pacti.iocontract.IoContract` internal representation of a Polyhedra contract according to the forms (1,2,3,4) above with a new function: `pacti.terms.polyhedra.loaders.polyhedra_contract_to_string`

**Comment by NicolasRouquette** [comment]
This issue requires a parser capability well beyond what is reasonable to tackle with the current regular expression approach. 

Defining the syntax of Pacti's Polyhedral terms as a formal grammar makes sense, which means defining a PEG parser and looking for available options here:
https://wiki.python.org/moin/LanguageParsing

The top two PEG libraries are [pyparsing](https://github.com/pyparsing/pyparsing) and [parsimonious](https://github.com/erikrose/parsimonious).

They both have very high stars on GitHub: 1.8K and 1.6K, respectively; however, there are a few reasons to choose pyparsing over parsimonious:
- parsimonious lacks a dedicated documentation website
- parsimonious' claimed speed is unlikely to be a significant factor because Polyhedral terms are reasonably short texts.
- pyparsing can generate railroad diagrams for the grammar, which can be helpful to understand/debug the grammar.

For these reasons, I propose using pyparsing to specify the Polyhedral term grammar and implement a corresponding parser.

**Comment by iincer** [comment]
Thanks for doing this research, @NicolasRouquette!
Implementing our own parser sounds very attractive, particularly as we support additional syntax in the future. This could allow us to show more consistency to the user.
Moving forward with this would be great. Do you think the time investment would be manageable?

**Comment by NicolasRouquette** [comment]
Creating the grammar to parse a generalized version of the [above table](https://github.com/pacti-org/pacti/issues/129#issuecomment-1435218828) is easy with pyparsing, which allows defining grammar in a similar way to a PEG parser.

If you are interested in following progress, see this branch:
https://github.com/pacti-org/pacti/tree/issue-129

The remaining work involves the following:
- During parsing, reduce the intermediate representation
   e.g., adding constants and factors for the same variable within a list of terms
- Mapping the intermediate representation to `PolyhedralTerm`

The time investment is about a day of work.

**Comment by iincer** [comment]
This will be a great addition. Thanks, @NicolasRouquette!

**Comment by NicolasRouquette** [comment]
FYI: I generated the railroad diagrams:
 This unfortunate

**Comment by NicolasRouquette** [comment]
This [commit](https://github.com/pacti-org/pacti/commit/950b3bcbb7326f685b4f2cb91b698f099c48c1c0) is WIP for the last step. 

The functionality for mapping `grammar.Expression` to `polyhedra.PolyhedralContract` is complete; however, 37 tests passed and 41 tests failed. This needs additional work...

**Comment by NicolasRouquette** [comment]
This [commit](https://github.com/pacti-org/pacti/commit/8f70a0874e49cae79b69b32b16e8dc53b11e1509) fixes all unit tests; however, I realize that we need to review the mapping. The [table](https://github.com/pacti-org/pacti/issues/129#issuecomment-1435218828) is incomplete because it does not address the general case supported by the grammar, which, in a compact form, is as follows:

```
term = only_variable | number_and_variable | only_number
signed_term = pp.Optional(symbol, default="+") + term

terms = signed_term + pp.ZeroOrMore(symbol + term)

abs_term = pp.Optional(floating_point_number) + "|" + terms + "|"

abs_or_term = abs_term | term

equality_expression = abs_or_terms + equality_operator + abs_or_terms
leq_expression = abs_or_terms + pp.OneOrMore("<=" + abs_or_terms)
geq_expression = abs_or_terms + pp.OneOrMore(">=" + abs_or_terms)
expression = equality_expression | leq_expression | geq_expression
```

The mapping is defined in https://github.com/pacti-org/pacti/blob/issue-129/src/pacti/terms/polyhedra/serializer.py

There are some examples here: https://github.com/pacti-org/pacti/blob/issue-129/examples/grammar/from_string.py

**Comment by NicolasRouquette** [comment]
Based on a recent discussion/review with @iincer, we concluded that:

1) For documentation purposes, we will make a markdown file with just the grammar rules instead of the railroad diagrams.

2) For the grammar rules:

- Add support for parentheses
- Restrict the syntax of absolute values to positive coefficients.

**Comment by NicolasRouquette** [comment]
The absolute value restriction may be too restrictive; consider this inequality:

```
|x+y| - |x-y| <= k
```

Geometrically, the solutions are in either 1 or 2 regions.
For example:

![image](https://user-images.githubusercontent.com/2359166/232252635-3957c2a8-feac-4548-b035-e3cfb110daf1.png) 

![image](https://user-images.githubusercontent.com/2359166/232252645-fd9e11d8-e305-4447-872c-8dfa70d9d6ae.png)

![image](https://user-images.githubusercontent.com/2359166/232252651-be991794-e59b-4c3a-a56f-056d40157cd9.png)

We can calculate the number of solution regions using without creating a plot:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.label.html#scipy.ndimage.label

Here is an example:

```python
import numpy as np
from scipy import ndimage

# Create a meshgrid for x and y values
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)
X, Y = np.meshgrid(x, y)

k = -2

# Calculate the inequality
Z = np.abs(X + Y) - np.abs(X - Y) - k

# Create a new Z array for the colorscale
# 0 = green
# 1 = red
Z_color = np.where(Z <= 0, 0, 1)

# Label contiguous regions in the Z_color array
labeled_array, num_features = ndimage.label(Z_color == 0)

# Print the number of contiguous green regions
print("Number of contiguous green regions:", num_features)
```

This prints:

```
Number of contiguous green regions: 2
```

We could incorporate this test to ensure that the solutions to each PolyhedralTerm are within a single contiguous geometrical region. What do you think @iincer ?

**Comment by iincer** [comment]
I like the use of `ndimage.label` to get the regions :-)
I agree that requiring the coefficients of absolute values to be nonnegative is restrictive. However, it is a way in which we are guaranteed get convex polyhedra from formulas. The examples you show give us nonconvex regions. This is equivalent to having specifications with logical ORs in them, which is currently not fully supported.

**Comment by NicolasRouquette** [comment]
Ah, if the requirement is a single convex region, then we should verify that the resulting set of linear inequalities yields a single convex region after expanding all absolute terms. We can use `scipy.spatial.ConvexHull` to iteratively keep track of the convexity of the inequalities as we add them one at a time.

**Comment by iincer** [comment]
I am pretty sure that requiring the nonnegativity of the coefficients multiplying the absolute values is sufficient, since *the only place* where non-convexity pops up is when we have `|exp| >= exp2`. This is evaluated to `(exp >= exp2) or (exp <= -exp2)`.

**Comment by NicolasRouquette** [comment]
So it is OK to have something like this:

$$
\Sigma_i k_i| a_i X + b_i Y + c_i Z | <= d
$$

for arbitrary values of $$a_i,b_i,c_i,d$$

as long as all $$k_i>=0$$

**Comment by iincer** [comment]
The $a_i$, $b_i$, $c_i$, and $d$ can be arbitrary. We only need $k_i \ge 0$.
